"use client";

import Link from "next/link";

import { TitleGenerator } from "@/components/title-generator";
import { Button } from "@/components/ui/button";

export default function OutlineTopic() {
  const handleConfirm = (title: string) => {
    // Navigate to paper list page
    window.location.href = `/outline/papers?title=${encodeURIComponent(title)}`;
  };

  return (
    <div className="space-y-8 p-6">
      {/* Header Section */}
      <div>
        <h1 className="mb-4 text-3xl font-bold text-gray-800 dark:text-gray-200">
          Section II: Paper Outline Generator
        </h1>

        <p className="mb-2 text-red-500">
          This tool generates a paper outline based on your title and reference
          paper list. In the next step, you can edit the reference paper list.
        </p>

        <p className="text-red-500">
          Finally, you can download a paper outline generated by LLM that
          includes the title, chapter outline, subsection outline and reference
          papers for content generation.
        </p>
      </div>

      {/* Title Generator Component */}
      <TitleGenerator onConfirm={handleConfirm} />

      {/* Back Button */}
      <div className="text-center">
        <Link href="/outline">
          <Button variant="outline">Back to Outline Home</Button>
        </Link>
      </div>
    </div>
  );
}
